# --------------------------------------
# Example Go app (existing)
# --------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-example-app
  namespace: demo
  labels:
    app: prometheus-example-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-example-app
  template:
    metadata:
      labels:
        app: prometheus-example-app
    spec:
      containers:
        - name: prometheus-example-app
          image: ghcr.io/prometheus/client_golang/example-random:latest
          ports:
            - containerPort: 8080
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-example-app
  namespace: demo
  labels:
    app: prometheus-example-app
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: prometheus-example-app

# --------------------------------------
# Java Spring Boot APM demo (new)
# --------------------------------------
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apm-demo
  namespace: demo
  labels:
    app: apm-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apm-demo
  template:
    metadata:
      labels:
        app: apm-demo
    spec:
      containers:
        - name: apm-demo
          image: ghcr.io/haiqal-uthm/apm-demo:latest
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: JAVA_OPTS
              value: "-Dserver.port=8080"
---
apiVersion: v1
kind: Service
metadata:
  name: apm-demo
  namespace: demo
  labels:
    app: apm-demo
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: apm-demo

# --------------------------------------
# ServiceMonitor for Prometheus Operator
# --------------------------------------
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-apps
  namespace: demo
  labels:
    release: kube-prometheus
spec:
  selector:
    matchExpressions:
      - { key: app, operator: In, values: ["prometheus-example-app", "apm-demo"] }
  namespaceSelector:
    matchNames:
      - demo
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
      honorLabels: true
