apiVersion: apps/v1
kind: Deployment
metadata:
  name: apm-demo
  namespace: demo
  labels:
    app: apm-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apm-demo
  template:
    metadata:
      labels:
        app: apm-demo
    spec:
      containers:
        - name: apm-demo
          image: ghcr.io/haiqal-uthm/apm-demo:latest
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: JAVA_OPTS
              value: "-Dserver.port=8080"
      imagePullSecrets:
        - name: ghcr-secret
